name: Build Github Page

on:
  push:
    branches:
      - build
jobs:
  build:
    name: Build Github Page
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Git Name And Email
        run: |
          $user = if ($env:USER_NAME) { $env:USER_NAME } else { 'github-actions[bot]' }
          $email = if ($env:USER_EMAIL) { $env:USER_EMAIL } else { 'github-actions[bot]@users.noreply.github.com' }
          git config --global user.name $user
          git config --global user.email $email
      - name: Set ToolChain
        run: |
          (new-object System.Net.WebClient).DownloadFile('https://github.com/rust-lang/mdBook/releases/download/v0.4.28/mdbook-v0.4.28-x86_64-pc-windows-msvc.zip','mdbook.zip')
          7z x -aoa -oC:\mdbook mdbook.zip
      - name: Build
        run: |
          $env:Path = "C:\mdbook;$env:Path"
          cd C:\ ; git clone --depth=1 https://github.com/axojhf/rust-course-fork -b main ; cd rust-course-fork ; mdbook build
          # cp ./assets/CNAME ./book/ ; cp ./assets/*.html ./book/ ; cp ./assets/sitemap.xml ./book/
          Copy-Item -Path ./assets/CNAME -Destination ./book/
          Copy-Item -Path ./assets/*.html -Destination ./book/
          Copy-Item -Path ./assets/sitemap.xml -Destination ./book/
          cd book ; git init ; git add . ; git commit -m 'deploy' ; git branch -M gh-pages
          git remote add origin git@github.com:axojhf/rust-course-fork.git ; git push -u -f origin gh-pages


